all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
all_joints_names:
- snout
- middle back
- front L foot
- front R foot
- hind L foot
- hind R foot
- L ear
- R ear
- tail base
- tail end
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
clahe: true
claheratio: 0.1
crop_sampling: hybrid
crop_size:
- 400
- 400
cropratio: 0.4
dataset: training-datasets/iteration-1/UnaugmentedDataSet_AnnotationCamTopFeb19/AnnotationCamTop_Comportement95shuffle1.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 1000
edge: false
emboss:
  alpha:
  - 0.0
  - 1.0
  embossratio: 0.1
  strength:
  - 0.5
  - 1.5
global_scale: 0.8
histeq: true
histeqratio: 0.1
init_weights: /home/comportement/Comportement-DLC-Train/AnnotationCamTop-Comportement-2022-02-19/dlc-models/iteration-0/AnnotationCamTopFeb19-trainset95shuffle1/train/snapshot-424500
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
max_shift: 0.4
metadataset: training-datasets/iteration-1/UnaugmentedDataSet_AnnotationCamTopFeb19/Documentation_data-AnnotationCamTop_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: mobilenet_v2_1.0
num_joints: 10
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
pre_resize: []
project_path: /home/comportement/Comportement-DLC-Train/AnnotationCamTop-Comportement-2022-02-19
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: false
sharpenratio: 0.3
